// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exam.Models;

namespace exam.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220628170751_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("exam.Models.File", b =>
                {
                    b.Property<int>("FileID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.HasKey("FileID", "TeamID");

                    b.HasIndex("TeamID");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            FileID = 1,
                            TeamID = 1,
                            FileExtension = "Extension1",
                            FileName = "FiletName1",
                            FileSize = 1
                        },
                        new
                        {
                            FileID = 2,
                            TeamID = 1,
                            FileExtension = "Extension2",
                            FileName = "FiletName2",
                            FileSize = 2
                        },
                        new
                        {
                            FileID = 3,
                            TeamID = 1,
                            FileExtension = "Extension3",
                            FileName = "FiletName3",
                            FileSize = 3
                        },
                        new
                        {
                            FileID = 4,
                            TeamID = 1,
                            FileExtension = "Extension4",
                            FileName = "FiletName4",
                            FileSize = 4
                        },
                        new
                        {
                            FileID = 5,
                            TeamID = 1,
                            FileExtension = "Extension5",
                            FileName = "FiletName5",
                            FileSize = 5
                        });
                });

            modelBuilder.Entity("exam.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MemberNickName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MemberSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            MemberName = "Member1",
                            MemberNickName = "Nick1",
                            MemberSurname = "Surname1",
                            OrganizationID = 1
                        },
                        new
                        {
                            MemberID = 2,
                            MemberName = "Member2",
                            MemberNickName = "Nick2",
                            MemberSurname = "Surname2",
                            OrganizationID = 2
                        },
                        new
                        {
                            MemberID = 3,
                            MemberName = "Member3",
                            MemberNickName = "Nick3",
                            MemberSurname = "Surname3",
                            OrganizationID = 3
                        },
                        new
                        {
                            MemberID = 4,
                            MemberName = "Member4",
                            MemberNickName = "Nick4",
                            MemberSurname = "Surname4",
                            OrganizationID = 4
                        },
                        new
                        {
                            MemberID = 5,
                            MemberName = "Member5",
                            MemberNickName = "Nick5",
                            MemberSurname = "Surname5",
                            OrganizationID = 5
                        });
                });

            modelBuilder.Entity("exam.Models.Membership", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberID", "TeamID");

                    b.HasIndex("TeamID");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            TeamID = 1,
                            MembershipDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 2,
                            TeamID = 2,
                            MembershipDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 3,
                            TeamID = 3,
                            MembershipDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 4,
                            TeamID = 4,
                            MembershipDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 5,
                            TeamID = 5,
                            MembershipDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("exam.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrganizationDomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            OrganizationID = 1,
                            OrganizationDomain = "Domain1",
                            OrganizationName = "Name1"
                        },
                        new
                        {
                            OrganizationID = 2,
                            OrganizationDomain = "Domain1",
                            OrganizationName = "Name2"
                        },
                        new
                        {
                            OrganizationID = 3,
                            OrganizationDomain = "Domain2",
                            OrganizationName = "Name3"
                        },
                        new
                        {
                            OrganizationID = 4,
                            OrganizationDomain = "Domain4",
                            OrganizationName = "Name4"
                        },
                        new
                        {
                            OrganizationID = 5,
                            OrganizationDomain = "Domain5",
                            OrganizationName = "Name5"
                        });
                });

            modelBuilder.Entity("exam.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("TeamDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeamID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            OrganizationID = 1,
                            TeamDescription = "Description1",
                            TeamName = "TeamName1"
                        },
                        new
                        {
                            TeamID = 2,
                            OrganizationID = 2,
                            TeamDescription = "Description2",
                            TeamName = "TeamName2"
                        },
                        new
                        {
                            TeamID = 3,
                            OrganizationID = 3,
                            TeamDescription = "Description3",
                            TeamName = "TeamName3"
                        },
                        new
                        {
                            TeamID = 4,
                            OrganizationID = 4,
                            TeamDescription = "Description4",
                            TeamName = "TeamName4"
                        },
                        new
                        {
                            TeamID = 5,
                            OrganizationID = 5,
                            TeamDescription = "Description5",
                            TeamName = "TeamName5"
                        });
                });

            modelBuilder.Entity("exam.Models.File", b =>
                {
                    b.HasOne("exam.Models.Team", "Team")
                        .WithMany("Files")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("exam.Models.Member", b =>
                {
                    b.HasOne("exam.Models.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationID");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("exam.Models.Membership", b =>
                {
                    b.HasOne("exam.Models.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("exam.Models.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("exam.Models.Team", b =>
                {
                    b.HasOne("exam.Models.Organization", "Organization")
                        .WithMany("Teamss")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("exam.Models.Member", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("exam.Models.Organization", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Teamss");
                });

            modelBuilder.Entity("exam.Models.Team", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
